first workflow done

diff --git a/.github/01-building-blocks.yml b/.github/01-building-blocks.yml
--- a/.github/01-building-blocks.yml
+++ b/.github/01-building-blocks.yml
@@ -1,19 +1,21 @@
-name: 01-building block
+name: 01-building-block
+
 on: push
 
 jobs:
-    echo-hello:
-      runs-on: ubuntu-latest
-      steps:
-        - name: say hello
-        run: echo "hello world !"
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say hello
+        run: echo "Hello World!"
 
-    echo-goodbye:
-      runs-on: ubuntu-latest
-      steps:
-        -name: failed step
-          run: |
-            echo "i will fail"
-            exit 1
-        -name: say-bye
-           run: echo "say bye"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+
+      - name: Say bye
+        run: echo "Say bye"
